//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        public int BranchId { get; set; }
        public string BranchLocation { get; set; }
    }
}
