//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBehavior
    {
        public int LogNo { get; set; }
        public string OfficerId { get; set; }
        public int MemberNo { get; set; }
        public string FIleStatus { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
    }
}
