//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileReferences
    {
        public int ReferenceNo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string OfficerId { get; set; }
        public int MemberNo { get; set; }
        public int FileNo { get; set; }
        public string FileStatus { get; set; }
        public string EmployerType { get; set; }
        public string Officer { get; set; }
    }
}
