//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberFile
    {
        public int FileNo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string OfficeId { get; set; }
        public int MemberNo { get; set; }
        public string EmployerType { get; set; }
        public byte[] LoanApplication { get; set; }
        public byte[] LoanAgreement { get; set; }
        public byte[] GuaranteeCertificate { get; set; }
        public byte[] Amortisation { get; set; }
        public byte[] ChequeCopy { get; set; }
        public byte[] Eligibility { get; set; }
        public byte[] RequestLetter { get; set; }
        public byte[] EmployerLetter { get; set; }
        public byte[] Quotation { get; set; }
        public byte[] Payslip { get; set; }
        public byte[] BankAccStatement { get; set; }
        public byte[] LoanStatement { get; set; }
        public byte[] VNPFStatement { get; set; }
        public byte[] StandingOrder { get; set; }
        public byte[] OffsetLetter { get; set; }
        public byte[] CustomerID { get; set; }
        public byte[] PaymentAdvice { get; set; }
        public byte[] Collateral { get; set; }
        public byte[] MaintenanceForm { get; set; }
        public byte[] DiaryMemo { get; set; }
        public System.Guid fileGUID { get; set; }
        public int FStatusId { get; set; }
    
        public virtual FileStatus FileStatus { get; set; }
        public virtual Refunds Refunds { get; set; }
    }
}
