//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Officers
    {
        public string OfficerId { get; set; }
        public int BranchId { get; set; }
        public int VnpfNo { get; set; }
        public int LoanNo { get; set; }
        public string EmpFname { get; set; }
        public string EmpMname { get; set; }
        public string EmpLname { get; set; }
        public int StatusId { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
