//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refunds
    {
        public int FileNo { get; set; }
        public System.DateTime RequestDate { get; set; }
        public byte[] PaymentRequest { get; set; }
        public byte[] LoanStatement { get; set; }
        public byte[] ReconciliationSheet { get; set; }
        public byte[] RefundChequeCopy { get; set; }
        public System.Guid fileGUID { get; set; }
    
        public virtual MemberFile MemberFile { get; set; }
    }
}
