//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vnpf_
    {
        public int RowId { get; set; }
        public Nullable<int> VNPF_Number { get; set; }
        public Nullable<int> Loan_Number { get; set; }
        public string Member_Fullname { get; set; }
        public string Loan_Balance { get; set; }
        public Nullable<double> Current_Repayment_Amount { get; set; }
    }
}
