//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace MFSL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberFile
    {
        public int FileNo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string OfficeId { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Only positive number allowed")]
        public int MemberNo { get; set; }
        public byte[] LoanApplication { get; set; }
        public byte[] OfferLetter { get; set; }
        public byte[] LoanAgreement { get; set; }
        public byte[] AcceptanceOffer { get; set; }
        public byte[] GuaranteeCertificate { get; set; }
        public byte[] Amortisation { get; set; }
        public byte[] ChequeCopy { get; set; }
        public byte[] Eligibility { get; set; }
        public byte[] Quotation { get; set; }
        public byte[] Payslip { get; set; }
        public byte[] LoanStatement { get; set; }
        public byte[] VNPFStatement { get; set; }
        public byte[] Other { get; set; }
        public System.Guid fileGUID { get; set; }
        public int FStatusId { get; set; }
    
        public virtual FileStatus FileStatus { get; set; }
    }
}
